<?php $registry = Mage::registry('loaded_registry'); ?>
<?php if($registry->getId()): ?>
    <h3><?php echo $registry->getEventName(); ?></h3>
    <p><strong><?php $this->__('Event Date:') ?> <?php echo $registry->getEventDate(); ?></strong></p>
    <p><strong><?php $this->__('Event Location:') ?> <?php echo $registry->getEventLocation(); ?></strong></p>
<?php else: ?>
    <h3>There was an error, the requested registry does not exist.</h3>
<?php endif; ?>